# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-BDB
version:      0.02
version_from: lib/Cache/BDB.pm
installdirs:  site
requires:
    BerkeleyDB:                    0.27
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
